nodeLinker: node-modules

plugins:
  - checksum: 113fae572c391623e3032d2be1c3eac64ca8d00cfb7fa62a4dab433b87bb66864a577acad63c0a16895869930a41587f409d9de2de69fd1ad539dee6ea9c6bdf
    path: .yarn/plugins/plugin-list.cjs
    spec: 'https://github.com/arendjr/yarn-plugin-list/releases/latest/download/yarn-plugin-list.js'

yarnPath: .yarn/releases/yarn-4.4.1.cjs
