name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    env:
      TEST_RESOURCES: test-resources
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup NodeJS 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: yarn install
        run: yarn install --immutable

      - name: yarn build
        run: yarn build

      - name: Allow unprivileged user namespace (ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0

      - name: UI test (macOS, windows)
        if: matrix.os != 'ubuntu-latest'
        run: yarn ui-test

      - name: UI test (linux)
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' yarn ui-test

      - name: Store UI test logs
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: logs-${{ matrix.os }}
          path: test-resources/settings/logs/*

      - name: Store UI Test screenshots
        uses: actions/upload-artifact@v4
        if: failure() || cancelled()
        with:
          name: screenshots-${{ matrix.os }}
          path: test-resources/screenshots/*.png

  check:
    if: always()
    runs-on: ubuntu-latest
    name: 🚦 Status Check
    needs: [main]
    steps:
      - name: ℹ️ Test Matrix Result
        run: |
          echo result = ${{ needs.main.result }}
      - name: ✅ Status Check - success
        if: ${{ needs.main.result == 'success' }}
        run: |
          echo "All tests successfully completed!"
          exit 0
      - name: ❌ Status Check - failure
        if: ${{ needs.main.result != 'success' }}
        run: |
          echo "Status Check failed!"
          exit 1
