name: Test with JUnit Reporter

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build webview
        run: yarn build:webview

      - name: Build project
        run: yarn build

      - name: Run linting
        run: yarn lint

      - name: Set up display for UI tests
        run: |
          export DISPLAY=:99
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Run UI tests with JUnit reporter
        run: yarn ui-test:run:junit
        continue-on-error: true

      - name: Upload test results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: UI Test Results
          path: test-results/junit.xml
          reporter: java-junit
          fail-on-error: false

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: test-results/
